url: https://www.dathinking.com
baseurl: https://www.dathinking.com/

title: Constra
email: info@constra.com
phone: +1 123456789

collections:
  solutions:
    output: true




markdown: kramdown
permalink: pretty